### ISSUE TITLE
Not compiling and running

### ISSUE THREAD

**Issue by suedadam** [splitice/ipstats#1]
Tried compiling and running this and it just sat at 100% CPU usage and didn't output anything.

Tried it with both PF_RING and without it.

**Comment by splitice** [comment]
How many IP addresses are on your machine?

We are running this on over 30 machines (Debian Linux, PF_RING) and do not experience what you are describing.

**Comment by suedadam** [comment]
254.

**Comment by splitice** [comment]
We havent tested it with more than 160 IP addresses, its likely that finding a no-collisions solution to the hash table will take quite a while for that many addresses (Birthday paradox).

Currently the hash table does not implement any buckets or open addressing.

**Comment by suedadam** [comment]
So should I try and leave it running for say ~30 minutes and see what happens?

**Comment by splitice** [comment]
Have you added a complete /24, or are your addresses somewhat random?

**Comment by suedadam** [comment]
It's a complete /24.

**Comment by suedadam** [comment]
Worked, I left it for about 8 minute and it started to work.

**Comment by splitice** [comment]
I made a commit that should make it faster to find a solution if a complete /24 is used. As well as added a scaling algorithm to make it work better when more IPs are added (temporary solution until the hash table is improved).

**Comment by suedadam** [comment]
sweet, thanks :)
