### ISSUE TITLE
Added Latency

### ISSUE THREAD

**Issue by suedadam** [splitice/ipstats#2]
When running this it adds quite a bit of latency (tested with pf_ring). When using a TCPPing script on it, the first packet took 1second to complete while the others took ~100ms. It caused a lot of lag, I'm not sure where the issue could originate but I just wanted to bring it to your attention.

**Comment by splitice** [comment]
The application does not interact at all with the delivery of packets, it acts as passive observer. Both libpcap and pf_ring backend modes will skip sampling packets if buffers fill.

We do not experience any change in latency on any of our servers where we have a version of this software deployed.

```
seq 0: tcp response from node-103-249-70-XXX.reverse.x4b.me (103.249.70.XXX) [open]  36.857 ms
seq 1: tcp response from node-103-249-70-XXX.reverse.x4b.me (103.249.70.XXX) [open]  37.419 ms
seq 2: tcp response from node-103-249-70-XXX.reverse.x4b.me (103.249.70.XXX) [open]  37.158 ms
```

The latency from the location performing the tcpping and the server running ipstats  is 36 - 38ms.

**Comment by suedadam** [comment]
What's the usual load (Mbps) on the servers at the time you did that?

**Comment by splitice** [comment]
That server I tested is only currently receiving and transmitting 80mbps / 20K PPS (Realtek Network card). 

Other servers are currently receiving 800mbps / 90-110K PPS currently (Intel Server Grade card with multiple RX queues).

This software has been tested at 9Gbps on an Intel 10GbE card at < 10% CPU (Xeon).

**Comment by suedadam** [comment]
When I was testing with about 300Mbps traffic inbound and 200Mbps outbound the results were 1s responses for the first packet and then normal responses. When I test it not with 20Mbps traffic it seems fine.

**Comment by splitice** [comment]
This script makes no differentiation between connection streams or anything like that, it sounds like your issue is unrelated to the software.

We have servers that are currently sustaining 180 - 250mbps in (80mbps out) that are responding not only correctly, but ipstats is running at <1% CPU usage.

**Comment by suedadam** [comment]
Well, as soon as I disabled it the latency issues stopped, are you running it with or without pf_ring?

**Comment by splitice** [comment]
With pf_ring.

**Comment by splitice** [comment]
Honeslty you probably need to look at your system and investigate what your bottleneck is. The software is not doing anything major, its just receiving a zero (or single copy) version of the packets received and sent - and counting them.

The only systems we have found where this even uses >1% CPU are small atom servers (its actually the FSB & IO which are limiting on those systems).

I have committed some optimizations and cleanups that come to mind, unfortunately I cant see any low hanging fruit - its pretty lean.

**Comment by suedadam** [comment]
Yeah, I think I found it out. The interference wasn't because of you but rather a weirdly old version of PF_RING. I'm running another test right now.

**Comment by suedadam** [comment]
Yup, seems fixed now. Sorry about that. 
Do you suggest anything to allow constant checking of this throughout the month? Using something like screen isn't really ideal because of the lack of ability to look at history in screen more than 100 lines (don't hold me to that number, not 100% sure).

**Comment by splitice** [comment]
We feed our data into Zabbix. There is a script in contrib that should be a good start. We have a custom UI on top of that to wrangle it all together though since Zabbix's UI doesn't hold up to the scale of data generated by software liked this (more than a thousand items per host).

Anything really will work (cacti, zabbix, graphite, etc).

**Comment by suedadam** [comment]
Okay cool, I'll try out the Zabbix one and if that doesn't work try and write one for cacti and send it your way :)

**Comment by splitice** [comment]
Feel free, Always open to contributions.

Seems like this is resolved, so Ill close it for now :)
