### ISSUE TITLE
Monitor based on destination address

### ISSUE THREAD

**Issue by HickeryJohn** [splitice/ipstats#3]
Hi,

Is it possible to make this monitor based on destination addresses as well? Doing something along the lines of adding BPF filters for the destination addresses so you can monitor traffic on the main interface to certain destinations (find bandwidth hogs)?

**Comment by splitice** [comment]
It could be done, but is not the purpose of the utility. Feel free to fork.

**Comment by HickeryJohn** [comment]
i sadly dont know how to make this change. are you able to make another branch with that change?

**Comment by splitice** [comment]
Sorry I have neither the time or motivation.
